#!/bin/bash
#MIT License
#
#Copyright (c) 2016 sch93nz
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.

# argument one should be the video 
# that you want to be displayed
# hard coded to be display=:0

echo "Filename $1" 
echo "Audio track $2"

# if first argument empty
if [ -z "$1" ];then
echo "failed to supplie a video file"
exit
fi

if [ -n "$1" ]; then
DISPLAY=:0 nohup vlc $1 --fullscreen --audio-track=$2 &
else
DISPLAY=:0 nohup vlc $1 --fullscreen &
fi

echo "Enjoy the show"
exit 1
